PR
phlyne/start pull request #3
Opened 2020-10-28 13:33 UTC by phlyne

2020-11-01 13:37 UTC, jacob1237 requested changes
Please check comments

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +    EXIT_SUCCESS = 0
You've moved these definitions under the `main()` function so now you can't actually import and use these constants from the outside of the current module. If you'll take a closer look at the unit tests, you'll find this:

```python
self.assertEqual(result, 0)
self.assertEqual(result, 3)
# ...
```

which means that you're duplicating your code there. It's much better to move these constants under the scope of your module (outside of `main`), then import them and use in the following way:

```python
import * from currency

self.assertEqual(result, EXIT_SUCCESS)
```

Imagine that the developer, who's using your module, is trying to check for these return codes. He can't import the codes, so he needs to reimplement constants values in his own module instead of reusing yours.

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +    reversed_check = False
No need to set this variable here. You're already doing that later in the code:

```python
reversed_check = len(args) > 2 and args[len(args)-1] in ("-r", "--reverse-quotation")
```

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +        print(
Now it's time to move these texts to the separate constants (or variables). It will make your code much cleaner, reduce the size of the `main()` function, and allow you to actually test the main() function for this text (if it outputs or not).

We can do this:
```python
TEXT_USAGE = (
    "usage: currency.py [valute code] [date: <format{yyyy-mm-dd}>]\n"
    "usage example: eur 2020-01-01\n"
    "this script has data from 1992-07-01\n"
    "in default program show direct quotations\n"
    "other arguments: [-h] [-a] [-e] [--exit-codes] [-r] [--reverse-quotation] [-u] [--usage]"
)

TEXT_RETURN_CODES = (
    "exit code 0: success\n"
    "exit code 1: currency-code format error\n"
    "exit code 2: date error(not in database or date in future)\n"
    "exit code 2: date error(not in database or date in future)\n"
)

# And then...
print(TEXT_USAGE)
return EXIT_REFERENCE

print(TEXT_RETURN_CODES)
return EXIT_REFERENCE
```

Also, I would recommend simplifying all your help sections by merging them into one. So that there will be no separate `-e` , `-u`, and keys like that. Instead, the user will get all the information from the "Usage" section, which will be accessible via `-h` (or when no parameters have been passed).

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +        return "cant find currency"
This is not the best way to return an error, because strings are tricky to work with and they're not intended to work as the error values. Let's replace it with:
```python
if currency not in html:
    raise ValueError("Currency not found")

# Other code...
```

Notice how I also reduce the nested `if` construction here. So instead of
```python
if currency in html:
    # ...
else:
    # ...
```
I do this:
```python
if currency not in html:
    # throw error

# Other code ...
```
so visually it's much easier to read.

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +    if date_check(dateinp):
It's possible to reduce the nesting level in this condition and make it much cleaner:
```python
if not date_check(dateinp):
    print("error: date input")
    return DATE_ERROR

# Other code...
```

2020-11-01 13:37 UTC, jacob1237 commented on currency.py
> +        html = str(urllib.request.urlopen(url).read())
When you run tests for the `main()` function, you're actually triggering a real internet connection. Remember what I've mentioned about the `download()` function?

Let's imagine for a second that we're using the paid API and we have a limit of 100 calls per month. When you don't mock the calls with your own dummy code, you're affecting this limit. So after running the tests multiple times, you won't be able to use the API anymore.

How is that supposed to work?

Also, this kind of testing requires a lot of time to execute the API calls. But unit tests must run very quickly

2020-11-01 13:37 UTC, jacob1237 commented on currency_tests.py
> +        result = currency.date_check("1992-06-20")
It's better to test the date one day before `1992-07-01` (which is `1992-06-30`), so we can be sure that the rule is not violated. But you're testing `1992-06-20`, which doesn't prove that `1992-07-01` is the valid lower bound of the allowed date range

2020-11-01 13:37 UTC, jacob1237 commented on currency_tests.py
> +        date = str(datetime.today().year) + '-' + str(datetime.today().month) + '-' + str(datetime.today().day + 1)
Don't use `datetime.today()` call multiple times. It's better to cache its value in a variable:
```python
today = datetime.today()
date = str(today.year) + '=' + str(today.month) ...
```
But in this particular case I would even use `strftime()`:
```python
date = datetime.today().strftime("%Y-%m-%d")
self.assertEqual(currency.date_check(date), False)
```
Looks much cleaner!

2020-11-01 13:37 UTC, jacob1237 commented on currency_tests.py
> +        html = open("F:/project/start/xml.txt")
This won't work on other machines. You have to use the path of your `currency_test.py` script, like this:

```python
import os

xml_path = os.path.join(
    os.path.dirname(os.path.realpath(__file__)),
    "xml.txt"
)

class CurrencyTest(unittest.TestCase):
    # ...
    def test_parse(self):
        html = open(xml_path)
        # ...
```

Also, there is a very useful operator in python which allows you to handle file closing in a hands-free way:
```python
def test_parse(self):
    # Once the `with` operator goes out of scope, it runs `f.close()` automatically
    with open(xml_path) as f:
        html = f.read()

    self.assertEqual(currency.parse(html, "usd", False), "30.9436")
```

2020-11-01 13:37 UTC, jacob1237 commented on currency_tests.py
> +        self.assertEqual(result, 0)
These return codes must be imported from the `currency` module:

```python
import * from currency

# ...
self.assertEqual(result, EXIT_SUCCESS)
```

2020-11-02 01:27 UTC, phlyne commented on currency_tests.py
> +        result = currency.date_check("1992-06-20")
here i just forgot how many days in June and just give day that 100% in June dx

2020-11-02 17:10 UTC, jacob1237 commented
Great work, approved :+1:

2020-11-02 17:10 UTC, merged